version: "3"
services:
  nacos:
    image: nacos/nacos-server:v2.2.2
    container_name: nacos-standalone
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    ports:
      - "8848:8848"